# Generated by Django 5.0.2 on 2024-09-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
